ne, Oython check_images.py

Traceback (most recent call last):
File "check_images.py", line 35, in <module>
from classify_images import classify_images
File "/Users /uuuumimmisia” Downloads/intropyproject-classify—pet-images/classify_images.py", line 24, in <module>
from classifier import classifier
File "/Users /uumumimiiay Downloads/intropyproject-classify—pet-images/classifier.py", line 15, in <module>
with open('intropyproject-classify—pet-images/imagenet1000_clsid_to_human.txt') as imagenet_classes_file:
FileNotFoundError: [Errno 2] No such file or directory: 'intropyproject-classify—pet—images/imagenet100@_clsid_to_human.
txt!
